services:
  database:
    image: docker.io/library/mysql:latest
    container_name: ecommerce-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: Ecommerce
    volumes:
      - ./mysql_db:/var/lib/mysql:Z
    restart: always